#!/usr/bin/env python3
"""
Behavior cloning warm-start for MaskablePPO.

Trains a MaskablePPO policy in two phases:
  1. Imitation phase: pre-train the policy by behavior cloning on
     trajectories generated by the project's scripted bots
     (``MediumBot`` / ``AdvancedBot``). The bots already use buffs,
     paralyze, and heal, so the cloned policy starts already aware
     that those abilities exist — solving the cold-start exploration
     problem that pure PPO struggles with on diverse action spaces.
  2. RL phase: standard MaskablePPO fine-tuning against the chosen
     opponent.

Requirements:
    pip install stable-baselines3 sb3-contrib

Usage:
    # Default: medium-vs-medium demos, then PPO vs medium.
    python examples/train_with_bc_warmstart.py

    # Larger demonstration set, harder demonstrator.
    python examples/train_with_bc_warmstart.py \\
        --demonstrator advanced --opponent advanced \\
        --n-episodes 100 --bc-epochs 10 --timesteps 500000
"""

import argparse
import sys
from pathlib import Path

try:
    from sb3_contrib import MaskablePPO  # noqa: F401  (import-time check)
except ImportError:
    print("Error: sb3-contrib is required. Install with: pip install sb3-contrib")
    sys.exit(1)

from reinforcetactics.rl import (
    load_scenarios_from_yaml,
    make_maskable_env,
    make_maskable_vec_env,
    make_warm_started_model,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--demonstrator", default="medium", choices=["simple", "medium", "advanced"])
    parser.add_argument("--opponent", default="medium", choices=["simple", "medium", "advanced", "random"])
    parser.add_argument("--n-episodes", type=int, default=50, help="Number of bot-vs-bot episodes to record")
    parser.add_argument("--bc-epochs", type=int, default=5, help="Behavior-cloning epochs")
    parser.add_argument("--bc-batch-size", type=int, default=64)
    parser.add_argument("--bc-lr", type=float, default=3e-4)
    parser.add_argument("--max-turns", type=int, default=200, help="Max turns per demonstration episode")
    parser.add_argument("--timesteps", type=int, default=200_000, help="PPO fine-tune timesteps")
    parser.add_argument("--n-envs", type=int, default=4, help="Parallel envs for PPO fine-tune")
    parser.add_argument("--map-file", default=None, help="Optional map CSV; default = random map")
    parser.add_argument(
        "--scenarios",
        default=None,
        help=(
            "Optional YAML file describing a curated mix of demonstration scenarios "
            "(see configs/bc_scenarios.yaml). When provided, --demonstrator / "
            "--opponent / --map-file / --n-episodes are ignored for the BC phase; "
            "the env used for PPO fine-tuning still respects --opponent / --map-file."
        ),
    )
    parser.add_argument("--save-path", default="models/bc_warmstart_ppo.zip")
    parser.add_argument("--seed", type=int, default=0)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # The PPO fine-tune environment. Single env is enough for BC (needs the
    # observation/action spaces); multi-env vec is used for fine-tuning.
    template_env = make_maskable_env(opponent=args.opponent, map_file=args.map_file)

    print("\n" + "=" * 60)
    print("Phase 1/2: Behavior cloning warm-start")
    print("=" * 60)

    scenarios = load_scenarios_from_yaml(args.scenarios) if args.scenarios else None
    if scenarios:
        print(f"  scenarios from {args.scenarios}: {len(scenarios)} entries")
        for sc in scenarios:
            print(
                f"    - {sc.name or sc.map_file or '<random>'}: "
                f"{sc.demonstrator} vs {sc.opponent}, "
                f"units={sc.enabled_units or 'all'}, "
                f"episodes={sc.n_episodes}, weight={sc.weight}"
            )
    else:
        print(f"  demonstrator={args.demonstrator}  opponent={args.opponent}")
        print(f"  episodes={args.n_episodes}  bc_epochs={args.bc_epochs}  batch={args.bc_batch_size}")

    model, dataset, bc_stats = make_warm_started_model(
        env=template_env,
        n_episodes=args.n_episodes,
        n_epochs=args.bc_epochs,
        demonstrator=args.demonstrator,
        opponent=args.demonstrator,  # bot-vs-bot for richer demos
        map_file=args.map_file,
        max_turns=args.max_turns,
        batch_size=args.bc_batch_size,
        learning_rate=args.bc_lr,
        seed=args.seed,
        ppo_kwargs={"verbose": 1},
        scenarios=scenarios,
    )

    print("\n--- BC summary ---")
    print(f"  demonstrations collected: {len(dataset)}")
    final = bc_stats[-1]
    print(f"  final loss: {final.loss:.4f}")
    print(f"  action_type accuracy: {final.accuracy_action_type:.3f}")
    print(f"  full-action accuracy: {final.accuracy_full:.3f}")

    print("\n" + "=" * 60)
    print(f"Phase 2/2: PPO fine-tune ({args.timesteps:,} timesteps)")
    print("=" * 60)

    if args.n_envs > 1:
        vec_env = make_maskable_vec_env(
            n_envs=args.n_envs,
            opponent=args.opponent,
            map_file=args.map_file,
            seed=args.seed,
            use_subprocess=True,
        )
        model.set_env(vec_env)

    model.learn(total_timesteps=args.timesteps, progress_bar=True)

    Path(args.save_path).parent.mkdir(parents=True, exist_ok=True)
    model.save(args.save_path)
    print(f"\nSaved warm-started + fine-tuned model to: {args.save_path}")


if __name__ == "__main__":
    main()
